-- =====================================================================
-- AuditNet · management-service · V1 — Esquema inicial (Entrega 1)
-- ---------------------------------------------------------------------
-- Reproduce la estructura que Hibernate generó durante la Entrega 1
-- para las tablas de las que este servicio es dueño:
--   organizaciones_cliente, sedes, roles, usuarios, usuarios_roles.
--
-- Diferencia deliberada respecto del esquema generado por Hibernate:
-- las claves foráneas usan nombres legibles (fk_<tabla>_<referencia>)
-- en lugar de los nombres aleatorios autogenerados. No cambia columnas,
-- tipos, nulabilidad, claves ni restricciones.
--
-- A partir de esta versión el esquema lo administra Flyway. Cualquier
-- cambio posterior se incorpora como una nueva migración (V2, V3, ...)
-- y nunca editando esta.
-- =====================================================================

CREATE TABLE organizaciones_cliente (
    id_organizacion bigint GENERATED BY DEFAULT AS IDENTITY,
    identificador   varchar(80)  NOT NULL,
    razon_social    varchar(160) NOT NULL,
    estado          varchar(30)  NOT NULL,
    CONSTRAINT organizaciones_cliente_pkey PRIMARY KEY (id_organizacion),
    CONSTRAINT uk_organizacion_identificador UNIQUE (identificador),
    CONSTRAINT uk_organizacion_razon_social UNIQUE (razon_social),
    CONSTRAINT organizaciones_cliente_estado_check
        CHECK (estado IN ('ACTIVO', 'DESHABILITADO'))
);

CREATE TABLE sedes (
    id_sede         bigint GENERATED BY DEFAULT AS IDENTITY,
    id_organizacion bigint       NOT NULL,
    nombre          varchar(120) NOT NULL,
    ubicacion       varchar(200) NOT NULL,
    estado          varchar(30)  NOT NULL,
    CONSTRAINT sedes_pkey PRIMARY KEY (id_sede),
    CONSTRAINT uk_sede_organizacion_nombre UNIQUE (id_organizacion, nombre),
    CONSTRAINT sedes_estado_check
        CHECK (estado IN ('ACTIVO', 'DESHABILITADO')),
    CONSTRAINT fk_sedes_organizacion
        FOREIGN KEY (id_organizacion) REFERENCES organizaciones_cliente (id_organizacion)
);

CREATE TABLE roles (
    id_rol      bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre      varchar(80)  NOT NULL,
    descripcion varchar(240) NOT NULL,
    estado      varchar(30)  NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id_rol),
    CONSTRAINT uk_rol_nombre UNIQUE (nombre),
    CONSTRAINT roles_estado_check
        CHECK (estado IN ('ACTIVO', 'DESHABILITADO'))
);

CREATE TABLE usuarios (
    id_usuario      bigint GENERATED BY DEFAULT AS IDENTITY,
    id_organizacion bigint       NOT NULL,
    nombre          varchar(140) NOT NULL,
    nombre_usuario  varchar(100) NOT NULL,
    email           varchar(160) NOT NULL,
    password_hash   varchar(120) NOT NULL,
    estado          varchar(30)  NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT uk_usuario_username UNIQUE (nombre_usuario),
    CONSTRAINT usuarios_estado_check
        CHECK (estado IN ('ACTIVO', 'DESHABILITADO')),
    CONSTRAINT fk_usuarios_organizacion
        FOREIGN KEY (id_organizacion) REFERENCES organizaciones_cliente (id_organizacion)
);

CREATE TABLE usuarios_roles (
    id_usuario bigint NOT NULL,
    id_rol     bigint NOT NULL,
    CONSTRAINT usuarios_roles_pkey PRIMARY KEY (id_usuario, id_rol),
    CONSTRAINT fk_usuarios_roles_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_usuarios_roles_rol
        FOREIGN KEY (id_rol) REFERENCES roles (id_rol)
);
