-- =====================================================================
-- AuditNet · management-service · V2 — Bitácora de auditoría de sistema
-- ---------------------------------------------------------------------
-- Puntos Mandatorios 2026: "Bitácora de auditoría de sistema (inicios de
-- sesión, creación de usuarios, asignaciones de privilegios, etc.)".
--
-- Decisiones:
--  * Tabla de solo inserción: un trigger rechaza UPDATE, DELETE y TRUNCATE,
--    para que ningún usuario de la aplicación pueda alterar el historial.
--  * Sin claves foráneas hacia usuarios u organizaciones: el registro debe
--    conservarse tal como ocurrió, aunque la entidad cambie después.
--    En un login rechazado el "actor" puede ser una identidad inexistente.
--  * evento no tiene CHECK: los tipos se validan en el código (enum) y así
--    agregar un tipo nuevo no requiere una migración.
-- =====================================================================

CREATE TABLE bitacora_sistema (
    id_evento           bigint GENERATED BY DEFAULT AS IDENTITY,
    fecha               timestamp(6) with time zone NOT NULL,
    evento              varchar(40)  NOT NULL,
    resultado           varchar(10)  NOT NULL,
    actor               varchar(160) NOT NULL,
    id_usuario_afectado bigint,
    id_organizacion     bigint,
    origen_ip           varchar(200),
    user_agent          varchar(300),
    correlacion         varchar(64),
    detalle             varchar(1000),
    CONSTRAINT bitacora_sistema_pkey PRIMARY KEY (id_evento),
    CONSTRAINT bitacora_sistema_resultado_check CHECK (resultado IN ('EXITO', 'FALLO'))
);

CREATE INDEX idx_bitacora_sistema_fecha ON bitacora_sistema (fecha DESC);
CREATE INDEX idx_bitacora_sistema_evento_fecha ON bitacora_sistema (evento, fecha DESC);

-- Función genérica reutilizable por las demás bitácoras de este servicio.
CREATE FUNCTION fn_bitacora_solo_insercion() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION 'La tabla % es una bitácora: solo admite inserciones (operación % rechazada)',
        TG_TABLE_NAME, TG_OP;
END;
$$;

CREATE TRIGGER trg_bitacora_sistema_sin_modificaciones
    BEFORE UPDATE OR DELETE ON bitacora_sistema
    FOR EACH ROW EXECUTE FUNCTION fn_bitacora_solo_insercion();

CREATE TRIGGER trg_bitacora_sistema_sin_truncate
    BEFORE TRUNCATE ON bitacora_sistema
    FOR EACH STATEMENT EXECUTE FUNCTION fn_bitacora_solo_insercion();
