-- =====================================================================
-- AuditNet · management-service · V3 — Bitácora de transacciones
-- ---------------------------------------------------------------------
-- Puntos Mandatorios 2026: "Bitácora de transacciones (referidas al
-- negocio). Ej: cambios de estados, modificaciones sobre entidades críticas".
--
-- Decisiones:
--  * Tabla compartida: la crea management-service y la escriben ambos
--    servicios (columna "servicio"). audit-core-service ya depende del
--    esquema de management (organizaciones y sedes), así que no se genera
--    una dependencia circular.
--  * valor_anterior / valor_nuevo: estado de la entidad en JSON (texto),
--    para reconstruir qué cambió en cada operación.
--  * Solo inserción: reutiliza la función de la V2 (rechaza UPDATE, DELETE
--    y TRUNCATE). Sin claves foráneas, igual que la bitácora de sistema.
-- =====================================================================

CREATE TABLE bitacora_transacciones (
    id_transaccion  bigint GENERATED BY DEFAULT AS IDENTITY,
    fecha           timestamp(6) with time zone NOT NULL,
    servicio        varchar(40)  NOT NULL,
    entidad         varchar(40)  NOT NULL,
    id_entidad      bigint,
    operacion       varchar(20)  NOT NULL,
    actor           varchar(160) NOT NULL,
    id_organizacion bigint,
    valor_anterior  text,
    valor_nuevo     text,
    correlacion     varchar(64),
    detalle         varchar(1000),
    CONSTRAINT bitacora_transacciones_pkey PRIMARY KEY (id_transaccion)
);

CREATE INDEX idx_bitacora_transacciones_fecha ON bitacora_transacciones (fecha DESC);
CREATE INDEX idx_bitacora_transacciones_entidad ON bitacora_transacciones (entidad, id_entidad, fecha DESC);
CREATE INDEX idx_bitacora_transacciones_organizacion ON bitacora_transacciones (id_organizacion, fecha DESC);

CREATE TRIGGER trg_bitacora_transacciones_sin_modificaciones
    BEFORE UPDATE OR DELETE ON bitacora_transacciones
    FOR EACH ROW EXECUTE FUNCTION fn_bitacora_solo_insercion();

CREATE TRIGGER trg_bitacora_transacciones_sin_truncate
    BEFORE TRUNCATE ON bitacora_transacciones
    FOR EACH STATEMENT EXECUTE FUNCTION fn_bitacora_solo_insercion();
