-- =====================================================================
-- AuditNet · audit-core-service · V1 — Esquema inicial (Entrega 1)
-- ---------------------------------------------------------------------
-- Reproduce la estructura que Hibernate generó durante la Entrega 1
-- para las tablas de las que este servicio es dueño:
--   tipos_dispositivo, dispositivos_red, configuraciones_dispositivo,
--   baselines_configuracion, reglas_baseline, auditorias_configuracion,
--   evaluaciones_regla_auditoria, hallazgos_auditoria.
--
-- Dependencia: referencia organizaciones_cliente y sedes, que crea la
-- V1 de management-service. Por eso management-service debe migrar
-- primero (en local: levantarlo antes que audit-core-service).
--
-- Diferencia deliberada respecto del esquema generado por Hibernate:
-- las claves foráneas usan nombres legibles (fk_<tabla>_<referencia>).
-- No cambia columnas, tipos, nulabilidad, claves ni restricciones.
-- Las mejoras detectadas (por ejemplo, los CHECK de estados) se
-- resuelven en migraciones posteriores, no editando esta.
-- =====================================================================

CREATE TABLE tipos_dispositivo (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre     varchar(100) NOT NULL,
    fabricante varchar(100) NOT NULL,
    familia    varchar(100) NOT NULL,
    activo     boolean      NOT NULL,
    CONSTRAINT tipos_dispositivo_pkey PRIMARY KEY (id)
);

CREATE TABLE dispositivos_red (
    id_dispositivo      bigint GENERATED BY DEFAULT AS IDENTITY,
    id_organizacion     bigint       NOT NULL,
    id_sede             bigint,
    id_tipo_dispositivo bigint       NOT NULL,
    nombre              varchar(120) NOT NULL,
    identificador       varchar(100) NOT NULL,
    fabricante          varchar(100) NOT NULL,
    criticidad          varchar(20)  NOT NULL,
    estado              varchar(20)  NOT NULL,
    CONSTRAINT dispositivos_red_pkey PRIMARY KEY (id_dispositivo),
    CONSTRAINT uk_dispositivos_red_identificador UNIQUE (identificador),
    CONSTRAINT dispositivos_red_criticidad_check
        CHECK (criticidad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    CONSTRAINT dispositivos_red_estado_check
        CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT fk_dispositivos_red_organizacion
        FOREIGN KEY (id_organizacion) REFERENCES organizaciones_cliente (id_organizacion),
    CONSTRAINT fk_dispositivos_red_sede
        FOREIGN KEY (id_sede) REFERENCES sedes (id_sede),
    CONSTRAINT fk_dispositivos_red_tipo
        FOREIGN KEY (id_tipo_dispositivo) REFERENCES tipos_dispositivo (id)
);

CREATE TABLE configuraciones_dispositivo (
    id_configuracion      bigint GENERATED BY DEFAULT AS IDENTITY,
    id_dispositivo        bigint                      NOT NULL,
    id_organizacion       bigint                      NOT NULL,
    version               integer                     NOT NULL,
    formato               varchar(20)                 NOT NULL,
    nombre_fuente         varchar(180)                NOT NULL,
    contenido_original    text                        NOT NULL,
    contenido_normalizado text                        NOT NULL,
    fecha_importacion     timestamp(6) with time zone NOT NULL,
    usuario_responsable   varchar(120)                NOT NULL,
    CONSTRAINT configuraciones_dispositivo_pkey PRIMARY KEY (id_configuracion),
    CONSTRAINT uk_config_dispositivo_version UNIQUE (id_dispositivo, version),
    CONSTRAINT configuraciones_dispositivo_formato_check
        CHECK (formato IN ('TEXTO', 'TXT', 'CFG')),
    CONSTRAINT fk_configuraciones_dispositivo_dispositivo
        FOREIGN KEY (id_dispositivo) REFERENCES dispositivos_red (id_dispositivo),
    CONSTRAINT fk_configuraciones_dispositivo_organizacion
        FOREIGN KEY (id_organizacion) REFERENCES organizaciones_cliente (id_organizacion)
);

CREATE TABLE baselines_configuracion (
    id_baseline         bigint GENERATED BY DEFAULT AS IDENTITY,
    id_organizacion     bigint       NOT NULL,
    id_tipo_dispositivo bigint       NOT NULL,
    nombre              varchar(140) NOT NULL,
    descripcion         varchar(500) NOT NULL,
    version             integer      NOT NULL,
    estado              varchar(20)  NOT NULL,
    CONSTRAINT baselines_configuracion_pkey PRIMARY KEY (id_baseline),
    CONSTRAINT uk_baseline_org_nombre UNIQUE (id_organizacion, nombre),
    CONSTRAINT baselines_configuracion_estado_check
        CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT fk_baselines_configuracion_organizacion
        FOREIGN KEY (id_organizacion) REFERENCES organizaciones_cliente (id_organizacion),
    CONSTRAINT fk_baselines_configuracion_tipo
        FOREIGN KEY (id_tipo_dispositivo) REFERENCES tipos_dispositivo (id)
);

CREATE TABLE reglas_baseline (
    id_regla      bigint GENERATED BY DEFAULT AS IDENTITY,
    id_baseline   bigint       NOT NULL,
    codigo        varchar(60)  NOT NULL,
    nombre        varchar(140) NOT NULL,
    descripcion   varchar(500) NOT NULL,
    tipo          varchar(30)  NOT NULL,
    patron        varchar(500) NOT NULL,
    severidad     varchar(20)  NOT NULL,
    recomendacion varchar(500) NOT NULL,
    estado        varchar(20)  NOT NULL,
    CONSTRAINT reglas_baseline_pkey PRIMARY KEY (id_regla),
    CONSTRAINT uk_regla_baseline_codigo UNIQUE (id_baseline, codigo),
    CONSTRAINT reglas_baseline_tipo_check
        CHECK (tipo IN ('DEBE_CONTENER', 'NO_DEBE_CONTENER')),
    CONSTRAINT reglas_baseline_severidad_check
        CHECK (severidad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    CONSTRAINT reglas_baseline_estado_check
        CHECK (estado IN ('ACTIVA', 'INACTIVA')),
    CONSTRAINT fk_reglas_baseline_baseline
        FOREIGN KEY (id_baseline) REFERENCES baselines_configuracion (id_baseline)
);

CREATE TABLE auditorias_configuracion (
    id_auditoria     bigint GENERATED BY DEFAULT AS IDENTITY,
    id_configuracion bigint                      NOT NULL,
    id_dispositivo   bigint                      NOT NULL,
    id_baseline      bigint                      NOT NULL,
    id_organizacion  bigint                      NOT NULL,
    fecha_ejecucion  timestamp(6) with time zone NOT NULL,
    ejecutado_por    varchar(120)                NOT NULL,
    total_reglas     integer                     NOT NULL,
    reglas_cumplidas integer                     NOT NULL,
    total_hallazgos  integer                     NOT NULL,
    severidad_maxima varchar(20)                 NOT NULL,
    resultado        varchar(30)                 NOT NULL,
    estado           varchar(20)                 NOT NULL,
    CONSTRAINT auditorias_configuracion_pkey PRIMARY KEY (id_auditoria),
    CONSTRAINT auditorias_configuracion_estado_check
        CHECK (estado IN ('FINALIZADA')),
    CONSTRAINT fk_auditorias_configuracion_configuracion
        FOREIGN KEY (id_configuracion) REFERENCES configuraciones_dispositivo (id_configuracion),
    CONSTRAINT fk_auditorias_configuracion_dispositivo
        FOREIGN KEY (id_dispositivo) REFERENCES dispositivos_red (id_dispositivo),
    CONSTRAINT fk_auditorias_configuracion_baseline
        FOREIGN KEY (id_baseline) REFERENCES baselines_configuracion (id_baseline),
    CONSTRAINT fk_auditorias_configuracion_organizacion
        FOREIGN KEY (id_organizacion) REFERENCES organizaciones_cliente (id_organizacion)
);

CREATE TABLE evaluaciones_regla_auditoria (
    id_evaluacion bigint GENERATED BY DEFAULT AS IDENTITY,
    id_auditoria  bigint       NOT NULL,
    id_regla      bigint       NOT NULL,
    codigo_regla  varchar(60)  NOT NULL,
    nombre_regla  varchar(140) NOT NULL,
    tipo          varchar(30)  NOT NULL,
    patron        varchar(500) NOT NULL,
    severidad     varchar(20)  NOT NULL,
    cumple        boolean      NOT NULL,
    evidencia     varchar(800) NOT NULL,
    CONSTRAINT evaluaciones_regla_auditoria_pkey PRIMARY KEY (id_evaluacion),
    CONSTRAINT uk_evaluacion_auditoria_regla UNIQUE (id_auditoria, id_regla),
    CONSTRAINT evaluaciones_regla_auditoria_tipo_check
        CHECK (tipo IN ('DEBE_CONTENER', 'NO_DEBE_CONTENER')),
    CONSTRAINT evaluaciones_regla_auditoria_severidad_check
        CHECK (severidad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    CONSTRAINT fk_evaluaciones_regla_auditoria_auditoria
        FOREIGN KEY (id_auditoria) REFERENCES auditorias_configuracion (id_auditoria),
    CONSTRAINT fk_evaluaciones_regla_auditoria_regla
        FOREIGN KEY (id_regla) REFERENCES reglas_baseline (id_regla)
);

CREATE TABLE hallazgos_auditoria (
    id_hallazgo     bigint GENERATED BY DEFAULT AS IDENTITY,
    id_auditoria    bigint                      NOT NULL,
    id_regla        bigint                      NOT NULL,
    id_dispositivo  bigint                      NOT NULL,
    id_baseline     bigint                      NOT NULL,
    id_organizacion bigint                      NOT NULL,
    codigo_regla    varchar(60)                 NOT NULL,
    nombre_regla    varchar(140)                NOT NULL,
    tipo_regla      varchar(30)                 NOT NULL,
    patron          varchar(500)                NOT NULL,
    severidad       varchar(20)                 NOT NULL,
    evidencia       varchar(800)                NOT NULL,
    recomendacion   varchar(500)                NOT NULL,
    estado          varchar(20)                 NOT NULL,
    fecha_deteccion timestamp(6) with time zone NOT NULL,
    CONSTRAINT hallazgos_auditoria_pkey PRIMARY KEY (id_hallazgo),
    CONSTRAINT uk_hallazgo_auditoria_regla UNIQUE (id_auditoria, id_regla),
    CONSTRAINT hallazgos_auditoria_tipo_regla_check
        CHECK (tipo_regla IN ('DEBE_CONTENER', 'NO_DEBE_CONTENER')),
    CONSTRAINT hallazgos_auditoria_severidad_check
        CHECK (severidad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    CONSTRAINT hallazgos_auditoria_estado_check
        CHECK (estado IN ('ABIERTO')),
    CONSTRAINT fk_hallazgos_auditoria_auditoria
        FOREIGN KEY (id_auditoria) REFERENCES auditorias_configuracion (id_auditoria),
    CONSTRAINT fk_hallazgos_auditoria_regla
        FOREIGN KEY (id_regla) REFERENCES reglas_baseline (id_regla),
    CONSTRAINT fk_hallazgos_auditoria_dispositivo
        FOREIGN KEY (id_dispositivo) REFERENCES dispositivos_red (id_dispositivo),
    CONSTRAINT fk_hallazgos_auditoria_baseline
        FOREIGN KEY (id_baseline) REFERENCES baselines_configuracion (id_baseline),
    CONSTRAINT fk_hallazgos_auditoria_organizacion
        FOREIGN KEY (id_organizacion) REFERENCES organizaciones_cliente (id_organizacion)
);
