-- =====================================================================
-- AuditNet · audit-core-service · V3 — Seguimiento de hallazgos (Bloque 4)
-- ---------------------------------------------------------------------
-- CU-005-001: el hallazgo tiene un estado de seguimiento que el usuario
-- autorizado puede actualizar, quedando registrado quién y cuándo.
--
-- 1. hallazgos_auditoria: se amplían los estados posibles y se guarda el
--    último cambio (usuario y fecha). La evidencia, la severidad y la
--    regla del hallazgo no se modifican nunca.
-- 2. seguimientos_hallazgo: historial completo de cambios de estado con
--    el comentario del usuario. Es de solo inserción (como las bitácoras).
-- =====================================================================

-- 1. Estados de seguimiento ---------------------------------------------
ALTER TABLE hallazgos_auditoria
    DROP CONSTRAINT hallazgos_auditoria_estado_check;
ALTER TABLE hallazgos_auditoria
    ADD CONSTRAINT hallazgos_auditoria_estado_check
        CHECK (estado IN ('ABIERTO', 'EN_REVISION', 'RESUELTO', 'ACEPTADO'));

ALTER TABLE hallazgos_auditoria
    ADD COLUMN fecha_estado timestamp(6) with time zone;
ALTER TABLE hallazgos_auditoria
    ADD COLUMN usuario_estado varchar(120);

CREATE INDEX ix_hallazgos_auditoria_estado ON hallazgos_auditoria (estado);
CREATE INDEX ix_hallazgos_auditoria_dispositivo ON hallazgos_auditoria (id_dispositivo);

-- 2. Historial de seguimiento ---------------------------------------------
CREATE TABLE seguimientos_hallazgo (
    id_seguimiento  bigint GENERATED BY DEFAULT AS IDENTITY,
    id_hallazgo     bigint                      NOT NULL,
    estado_anterior varchar(20)                 NOT NULL,
    estado_nuevo    varchar(20)                 NOT NULL,
    comentario      varchar(1000),
    usuario         varchar(120)                NOT NULL,
    fecha           timestamp(6) with time zone NOT NULL,
    CONSTRAINT seguimientos_hallazgo_pkey PRIMARY KEY (id_seguimiento),
    CONSTRAINT ck_seguimientos_hallazgo_estado_anterior
        CHECK (estado_anterior IN ('ABIERTO', 'EN_REVISION', 'RESUELTO', 'ACEPTADO')),
    CONSTRAINT ck_seguimientos_hallazgo_estado_nuevo
        CHECK (estado_nuevo IN ('ABIERTO', 'EN_REVISION', 'RESUELTO', 'ACEPTADO')),
    CONSTRAINT fk_seguimientos_hallazgo_hallazgo
        FOREIGN KEY (id_hallazgo) REFERENCES hallazgos_auditoria (id_hallazgo)
);

CREATE INDEX ix_seguimientos_hallazgo_hallazgo ON seguimientos_hallazgo (id_hallazgo, fecha);

-- El historial no se modifica ni se borra.
CREATE FUNCTION fn_seguimiento_hallazgo_solo_insercion() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'seguimientos_hallazgo es de solo inserción: no se permite %', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_seguimientos_hallazgo_sin_cambios
    BEFORE UPDATE OR DELETE ON seguimientos_hallazgo
    FOR EACH ROW EXECUTE FUNCTION fn_seguimiento_hallazgo_solo_insercion();

CREATE TRIGGER tr_seguimientos_hallazgo_sin_truncate
    BEFORE TRUNCATE ON seguimientos_hallazgo
    FOR EACH STATEMENT EXECUTE FUNCTION fn_seguimiento_hallazgo_solo_insercion();
